// Generated by CoffeeScript 1.12.2
(function() {
  var ChatInput, Image, React, ReactNative, ScrollView, StyleSheet, Text, TextInput, TouchableHighlight, View, styles;

  React = require('react');

  ReactNative = require('react-native');

  Image = ReactNative.Image, Text = ReactNative.Text, TextInput = ReactNative.TextInput, View = ReactNative.View, StyleSheet = ReactNative.StyleSheet, TouchableHighlight = ReactNative.TouchableHighlight, ScrollView = ReactNative.ScrollView;

  ChatInput = React.createClass({displayName: "ChatInput",
    getInitialState: function() {
      return {
        text: '',
        height: 35
      };
    },
    submit: function() {
      this.props.onSubmit(this.state.text);
      this.input.clear(0);
      return this.setState({
        text: '',
        height: 35
      });
    },
    render: function() {
      return React.createElement(View, {
        "style": styles.textInput
      }, React.createElement(TextInput, {
        "editable": this.props.editable,
        "ref": ((function(_this) {
          return function(ref) {
            return _this.input = ref;
          };
        })(this)),
        "style": [
          styles.textbox, {
            height: this.state.height
          }
        ],
        "multiline": true,
        "placeholder": 'Message #' + this.props.name + '...',
        "placeholderTextColor": '#888888',
        "onChange": ((function(_this) {
          return function(event) {
            return _this.setState({
              text: event.nativeEvent.text,
              height: Math.min(67.43, event.nativeEvent.contentSize.height)
            });
          };
        })(this)),
        "underlineColorAndroid": '#282828'
      }), React.createElement(TouchableHighlight, {
        "style": styles.button,
        "onPress": this.submit
      }, React.createElement(Image, {
        "style": styles.send,
        "source": require('./img/send.png')
      })));
    }
  });

  styles = StyleSheet.create({
    textInput: {
      borderTopColor: '#111111',
      borderTopWidth: 1,
      flexDirection: 'row',
      backgroundColor: '#282828',
      elevation: 5
    },
    button: {
      flex: 1,
      justifyContent: 'center'
    },
    textbox: {
      paddingTop: 8,
      flex: 10,
      color: '#FFFFFF'
    },
    send: {
      marginLeft: 10,
      height: 15,
      width: 15
    }
  });

  module.exports = ChatInput;

}).call(this);
