// Generated by CoffeeScript 1.12.2
(function() {
  var Header, Image, ListView, React, ReactNative, StyleSheet, Text, TouchableHighlight, View, styles;

  React = require('react');

  ReactNative = require('react-native');

  Image = ReactNative.Image, Text = ReactNative.Text, View = ReactNative.View, StyleSheet = ReactNative.StyleSheet, TouchableHighlight = ReactNative.TouchableHighlight, ListView = ReactNative.ListView;

  Header = React.createClass({displayName: "Header",
    openSettings: function() {
      this.props.navigator.selectedChannel = this.props.name;
      return this.props.navigator.push({
        name: 'serversettings'
      });
    },
    openPinned: function() {
      this.props.navigator.selectedChannel = this.props.name;
      return this.props.navigator.push({
        name: 'pinned'
      });
    },
    render: function() {
      return React.createElement(View, {
        "style": styles.header
      }, React.createElement(TouchableHighlight, {
        "style": {
          flex: 1
        },
        "onPress": this.props.openLeft
      }, React.createElement(Image, {
        "style": styles.img,
        "source": require('./img/list.png')
      })), React.createElement(TouchableHighlight, {
        "style": {
          flex: 2.2
        },
        "onPress": this.openSettings
      }, React.createElement(Text, {
        "style": styles.text
      }, '#' + this.props.name + ' \u25be')), React.createElement(Text, {
        "style": {
          flex: 6
        }
      }), React.createElement(TouchableHighlight, {
        "style": {
          flex: 1
        },
        "onPress": this.openPinned
      }, React.createElement(Image, {
        "style": styles.img,
        "source": require('./img/pinned.png')
      })), React.createElement(TouchableHighlight, {
        "style": {
          flex: 1
        },
        "onPress": this.props.openRight
      }, React.createElement(Image, {
        "style": styles.img,
        "source": require('./img/people.png')
      })));
    }
  });

  styles = StyleSheet.create({
    header: {
      flexDirection: 'row',
      backgroundColor: '#222222',
      borderBottomColor: '#000000',
      borderBottomWidth: 1,
      elevation: 5
    },
    text: {
      color: '#FFFFFF',
      padding: 12
    },
    img: {
      marginLeft: 10,
      marginTop: 15,
      height: 15,
      width: 15
    }
  });

  module.exports = Header;

}).call(this);
