// Generated by CoffeeScript 1.12.2
(function() {
  var AddChannel, AppRegistry, ChatProject, Image, MainScene, Navigator, PinnedMessages, React, ReactNative, ServerSettings, StyleSheet, Text, View;

  React = require('react');

  ReactNative = require('react-native');

  MainScene = require('./MainScene');

  ServerSettings = require('./ServerSettings');

  PinnedMessages = require('./PinnedMessages');

  AddChannel = require('./AddChannel');

  AppRegistry = ReactNative.AppRegistry, StyleSheet = ReactNative.StyleSheet, Text = ReactNative.Text, View = ReactNative.View, Image = ReactNative.Image, Navigator = ReactNative.Navigator;

  ChatProject = React.createClass({displayName: "ChatProject",
    render: function() {
      return React.createElement(Navigator, {
        "initialRoute": {
          name: 'main',
          index: 0
        },
        "sceneStyle": {
          backgroundColor: '#000000'
        },
        "renderScene": ((function(_this) {
          return function(route, navigator) {
            switch (route.name) {
              case 'main':
                return React.createElement(MainScene, {
                  "navigator": navigator
                });
              case 'serversettings':
                return React.createElement(ServerSettings, {
                  "channelName": navigator.selectedChannel,
                  "navigator": navigator
                });
              case 'pinned':
                return React.createElement(PinnedMessages, {
                  "channelName": navigator.selectedChannel,
                  "navigator": navigator
                });
              case 'addchannel':
                return React.createElement(AddChannel, {
                  "navigator": navigator,
                  "onAddChannel": navigator.onAddChannel
                });
            }
          };
        })(this)),
        "configureScene": ((function(_this) {
          return function(route, routeStack) {
            return Navigator.SceneConfigs.FloatFromBottom;
          };
        })(this))
      });
    }
  });

  AppRegistry.registerComponent('ChatProject', (function(_this) {
    return function() {
      return ChatProject;
    };
  })(this));

}).call(this);
