// Generated by CoffeeScript 1.12.2
(function() {
  var Image, React, ReactNative, ScrollView, StyleSheet, Text, UserPane, View, bar, styles;

  React = require('react');

  ReactNative = require('react-native');

  Text = ReactNative.Text, View = ReactNative.View, StyleSheet = ReactNative.StyleSheet, Image = ReactNative.Image, ScrollView = ReactNative.ScrollView;

  bar = '\u23af\u23af\u23af\u23af\u23af\u23af\u23af\u23af\u23af\u23af\u23af\u23af\u23af\u23af\u23af';

  UserPane = React.createClass({displayName: "UserPane",
    getInitialState: function() {
      return {
        elements: []
      };
    },
    componentWillMount: function() {
      return this.setState({
        elements: this.props.users.map(this.renderRow)
      });
    },
    renderRow: function(user, i) {
      return React.createElement(View, {
        "key": i,
        "style": {
          flexDirection: 'row'
        }
      }, React.createElement(View, {
        "flexDirection": 'row'
      }, React.createElement(Image, {
        "style": styles.avatar,
        "source": {
          uri: 'http://fathomless-retreat-96857.herokuapp.com' + user.avatar
        }
      }), React.createElement(Image, {
        "style": styles.online,
        "source": {
          uri: 'https://images6.alphacoders.com/405/405735.jpg'
        }
      })), React.createElement(View, null, React.createElement(Text, {
        "style": styles.text
      }, user.username), React.createElement(Text, {
        "style": styles.divider
      }, bar + bar)));
    },
    render: function() {
      return React.createElement(View, {
        "style": styles.container
      }, React.createElement(View, {
        "style": styles.header
      }, React.createElement(Text, {
        "style": [
          styles.text, {
            padding: 13.5
          }
        ]
      }, "Users")), React.createElement(ScrollView, null, React.createElement(Text, {
        "style": styles.text
      }, 'ONLINE - ' + this.props.users.length), this.state.elements, React.createElement(Text, {
        "style": styles.text
      }, 'OFFLINE - 0')));
    }
  });

  styles = StyleSheet.create({
    header: {
      flexDirection: 'row',
      backgroundColor: '#282828'
    },
    container: {
      flex: 1,
      flexDirection: 'column',
      backgroundColor: '#222222'
    },
    text: {
      padding: 12,
      fontSize: 12,
      color: '#FFFFFF'
    },
    avatar: {
      marginTop: 7,
      marginBottom: 7,
      marginLeft: 15,
      marginRight: 15,
      height: 30,
      width: 30,
      borderRadius: 15,
      overlayColor: '#222222'
    },
    divider: {
      paddingTop: 1.5,
      paddingLeft: 5,
      fontSize: 8,
      color: '#444444'
    },
    online: {
      height: 10,
      width: 10,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: '#222222',
      right: 25,
      top: 25
    }
  });

  module.exports = UserPane;

}).call(this);
