// Generated by CoffeeScript 1.12.2
(function() {
  var Dimensions, Image, React, ReactNative, StyleSheet, Text, TouchableHighlight, View, Whiteboard, WhiteboardContainer, styles;

  React = require('react');

  ReactNative = require('react-native');

  Whiteboard = require('./Whiteboard');

  Dimensions = require('Dimensions');

  Text = ReactNative.Text, View = ReactNative.View, StyleSheet = ReactNative.StyleSheet, TouchableHighlight = ReactNative.TouchableHighlight, Image = ReactNative.Image;

  WhiteboardContainer = React.createClass({displayName: "WhiteboardContainer",
    undo: function() {
      return this.whiteboard.undo();
    },
    redo: function() {
      return this.whiteboard.redo();
    },
    clear: function() {
      return this.whiteboard.clear();
    },
    paintRemote: function(obj) {
      return this.whiteboard.paintRemote(obj);
    },
    onPaint: function(event) {},
    render: function() {
      return React.createElement(View, {
        "style": styles.container
      }, React.createElement(Whiteboard, {
        "ref": ((function(_this) {
          return function(ref) {
            return _this.whiteboard = ref;
          };
        })(this)),
        "style": {
          width: Dimensions.get('window').width,
          height: Dimensions.get('window').width
        },
        "onPaint": this.onPaint
      }), React.createElement(View, {
        "flexDirection": 'row'
      }, React.createElement(TouchableHighlight, {
        "onPress": this.undo,
        "style": {
          flex: 1
        }
      }, React.createElement(Text, {
        "style": [
          styles.text, {
            textAlign: 'center'
          }
        ]
      }, "UNDO")), React.createElement(TouchableHighlight, {
        "onPress": this.redo,
        "style": {
          flex: 1
        }
      }, React.createElement(Text, {
        "style": [
          styles.text, {
            textAlign: 'center'
          }
        ]
      }, "REDO")), React.createElement(TouchableHighlight, {
        "onPress": this.clear,
        "style": {
          flex: 1
        }
      }, React.createElement(Text, {
        "style": [
          styles.text, {
            textAlign: 'center'
          }
        ]
      }, "CLEAR"))));
    }
  });

  styles = StyleSheet.create({
    text: {
      padding: 12,
      color: 'white'
    },
    container: {
      backgroundColor: '#222222',
      elevation: 3
    }
  });

  module.exports = WhiteboardContainer;

}).call(this);
